import type { MunicipalityLite } from "@/lib/checkout-flow";

export const MUNICIPALITIES_FALLBACK: MunicipalityLite[] = [
  {
    teryt_code: "1261011",
    name: "Krakow",
    full_name: "gmina miejska Krakow",
    type: "miasto_na_prawach_powiatu",
    voivodeship: "malopolskie",
    office_name: "Urzad Miasta Krakowa",
    office_address: "pl. Wszystkich Swietych 3-4, 31-004 Krakow",
    office_phone: "(12) 616 16 16",
    office_bip_url: "https://www.bip.krakow.pl",
    accepts_epuap: true,
    accepts_mail: true,
    accepts_in_person: true,
  },
  {
    teryt_code: "1465011",
    name: "Warszawa",
    full_name: "miasto stoleczne Warszawa",
    type: "miasto_na_prawach_powiatu",
    voivodeship: "mazowieckie",
    office_name: "Urzad m.st. Warszawy",
    office_address: "pl. Bankowy 3/5, 00-950 Warszawa",
    office_phone: "19115",
    office_bip_url: "https://bip.warszawa.pl",
    accepts_epuap: true,
    accepts_mail: true,
    accepts_in_person: true,
  },
  {
    teryt_code: "1465011-ursynow",
    name: "Warszawa Ursynow",
    full_name: "dzielnica m.st. Warszawy Ursynow",
    type: "dzielnica",
    voivodeship: "mazowieckie",
    office_name: "Urzad Dzielnicy Ursynow m.st. Warszawy",
    office_address: "al. KEN 61, 02-777 Warszawa",
    office_phone: "22 443 71 00",
    office_bip_url: "https://ursynow.um.warszawa.pl",
    accepts_epuap: true,
    accepts_mail: true,
    accepts_in_person: true,
  },
  {
    teryt_code: "1465011-wlochy",
    name: "Warszawa Wlochy",
    full_name: "dzielnica m.st. Warszawy Wlochy",
    type: "dzielnica",
    voivodeship: "mazowieckie",
    office_name: "Urzad Dzielnicy Wlochy m.st. Warszawy",
    office_address: "al. Krakowska 257, 02-133 Warszawa",
    office_phone: "22 443 50 00",
    office_bip_url: "https://wlochy.um.warszawa.pl",
    accepts_epuap: true,
    accepts_mail: true,
    accepts_in_person: true,
  },
  {
    teryt_code: "1465011-mokotow",
    name: "Warszawa Mokotow",
    full_name: "dzielnica m.st. Warszawy Mokotow",
    type: "dzielnica",
    voivodeship: "mazowieckie",
    office_name: "Urzad Dzielnicy Mokotow m.st. Warszawy",
    office_address: "ul. Rakowiecka 25/27, 02-517 Warszawa",
    office_phone: "22 443 64 00",
    office_bip_url: "https://mokotow.um.warszawa.pl",
    accepts_epuap: true,
    accepts_mail: true,
    accepts_in_person: true,
  },
  {
    teryt_code: "1465011-bielany",
    name: "Warszawa Bielany",
    full_name: "dzielnica m.st. Warszawy Bielany",
    type: "dzielnica",
    voivodeship: "mazowieckie",
    office_name: "Urzad Dzielnicy Bielany m.st. Warszawy",
    office_address: "ul. Zeromskiego 29, 01-882 Warszawa",
    office_phone: "22 443 10 00",
    office_bip_url: "https://bielany.um.warszawa.pl",
    accepts_epuap: true,
    accepts_mail: true,
    accepts_in_person: true,
  },
  {
    teryt_code: "3064011",
    name: "Poznan",
    full_name: "gmina miejska Poznan",
    type: "miasto_na_prawach_powiatu",
    voivodeship: "wielkopolskie",
    office_name: "Urzad Miasta Poznania",
    office_address: "pl. Kolegiacki 17, 61-841 Poznan",
    office_phone: "(61) 878 56 00",
    office_bip_url: "https://bip.poznan.pl",
    accepts_epuap: true,
    accepts_mail: true,
    accepts_in_person: true,
  },
  {
    teryt_code: "0264011",
    name: "Wroclaw",
    full_name: "gmina miejska Wroclaw",
    type: "miasto_na_prawach_powiatu",
    voivodeship: "dolnoslaskie",
    office_name: "Urzad Miejski Wroclawia",
    office_address: "pl. Nowy Targ 1-8, 50-141 Wroclaw",
    office_phone: "71 777 77 77",
    office_bip_url: "https://bip.um.wroc.pl",
    accepts_epuap: true,
    accepts_mail: true,
    accepts_in_person: true,
  },
  {
    teryt_code: "2261011",
    name: "Gdansk",
    full_name: "gmina miejska Gdansk",
    type: "miasto_na_prawach_powiatu",
    voivodeship: "pomorskie",
    office_name: "Urzad Miejski w Gdansku",
    office_address: "ul. Nowe Ogrody 8/12, 80-803 Gdansk",
    office_phone: "58 323 60 00",
    office_bip_url: "https://www.bip.gdansk.pl",
    accepts_epuap: true,
    accepts_mail: true,
    accepts_in_person: true,
  },
];
