create table if not exists public.municipalities (
  id bigint generated by default as identity primary key,
  teryt_code text unique not null,
  name text not null,
  full_name text not null,
  type text not null,
  county text not null,
  voivodeship text not null,
  office_name text not null,
  office_address text,
  office_phone text,
  office_email text,
  office_bip_url text,
  accepts_epuap boolean not null default true,
  accepts_mail boolean not null default true,
  accepts_in_person boolean not null default true,
  registration_info text,
  notes text
);

create index if not exists municipalities_name_idx
  on public.municipalities using btree (name);

create index if not exists municipalities_full_name_idx
  on public.municipalities using btree (full_name);

create index if not exists municipalities_voivodeship_idx
  on public.municipalities using btree (voivodeship);
